// Code generated by go-swagger; DO NOT EDIT.

package schemas

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/jimdickinson/stargoat/pkg/models"
)

// NewAddTableParams creates a new AddTableParams object
// with the default values initialized.
func NewAddTableParams() *AddTableParams {
	var ()
	return &AddTableParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAddTableParamsWithTimeout creates a new AddTableParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAddTableParamsWithTimeout(timeout time.Duration) *AddTableParams {
	var ()
	return &AddTableParams{

		timeout: timeout,
	}
}

// NewAddTableParamsWithContext creates a new AddTableParams object
// with the default values initialized, and the ability to set a context for a request
func NewAddTableParamsWithContext(ctx context.Context) *AddTableParams {
	var ()
	return &AddTableParams{

		Context: ctx,
	}
}

// NewAddTableParamsWithHTTPClient creates a new AddTableParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAddTableParamsWithHTTPClient(client *http.Client) *AddTableParams {
	var ()
	return &AddTableParams{
		HTTPClient: client,
	}
}

/*AddTableParams contains all the parameters to send to the API endpoint
for the add table operation typically these are written to a http.Request
*/
type AddTableParams struct {

	/*XCassandraToken
	  The token returned from the authorization endpoint. Use this token in each request.

	*/
	XCassandraToken string
	/*Body
	  Table object that needs to be added to the keyspace

	*/
	Body *models.TableAdd
	/*KeyspaceName
	  Name of the keyspace to use for the request.

	*/
	KeyspaceName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the add table params
func (o *AddTableParams) WithTimeout(timeout time.Duration) *AddTableParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add table params
func (o *AddTableParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add table params
func (o *AddTableParams) WithContext(ctx context.Context) *AddTableParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add table params
func (o *AddTableParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add table params
func (o *AddTableParams) WithHTTPClient(client *http.Client) *AddTableParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add table params
func (o *AddTableParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXCassandraToken adds the xCassandraToken to the add table params
func (o *AddTableParams) WithXCassandraToken(xCassandraToken string) *AddTableParams {
	o.SetXCassandraToken(xCassandraToken)
	return o
}

// SetXCassandraToken adds the xCassandraToken to the add table params
func (o *AddTableParams) SetXCassandraToken(xCassandraToken string) {
	o.XCassandraToken = xCassandraToken
}

// WithBody adds the body to the add table params
func (o *AddTableParams) WithBody(body *models.TableAdd) *AddTableParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the add table params
func (o *AddTableParams) SetBody(body *models.TableAdd) {
	o.Body = body
}

// WithKeyspaceName adds the keyspaceName to the add table params
func (o *AddTableParams) WithKeyspaceName(keyspaceName string) *AddTableParams {
	o.SetKeyspaceName(keyspaceName)
	return o
}

// SetKeyspaceName adds the keyspaceName to the add table params
func (o *AddTableParams) SetKeyspaceName(keyspaceName string) {
	o.KeyspaceName = keyspaceName
}

// WriteToRequest writes these params to a swagger request
func (o *AddTableParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-Cassandra-Token
	if err := r.SetHeaderParam("X-Cassandra-Token", o.XCassandraToken); err != nil {
		return err
	}

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param keyspaceName
	if err := r.SetPathParam("keyspaceName", o.KeyspaceName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
