// Code generated by go-swagger; DO NOT EDIT.

package schemas

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/jimdickinson/stargoat/pkg/models"
)

// NewAddColumnParams creates a new AddColumnParams object
// with the default values initialized.
func NewAddColumnParams() *AddColumnParams {
	var ()
	return &AddColumnParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAddColumnParamsWithTimeout creates a new AddColumnParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAddColumnParamsWithTimeout(timeout time.Duration) *AddColumnParams {
	var ()
	return &AddColumnParams{

		timeout: timeout,
	}
}

// NewAddColumnParamsWithContext creates a new AddColumnParams object
// with the default values initialized, and the ability to set a context for a request
func NewAddColumnParamsWithContext(ctx context.Context) *AddColumnParams {
	var ()
	return &AddColumnParams{

		Context: ctx,
	}
}

// NewAddColumnParamsWithHTTPClient creates a new AddColumnParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAddColumnParamsWithHTTPClient(client *http.Client) *AddColumnParams {
	var ()
	return &AddColumnParams{
		HTTPClient: client,
	}
}

/*AddColumnParams contains all the parameters to send to the API endpoint
for the add column operation typically these are written to a http.Request
*/
type AddColumnParams struct {

	/*XCassandraToken
	  The token returned from the authorization endpoint. Use this token in each request.

	*/
	XCassandraToken string
	/*Body*/
	Body *models.ColumnDefinition
	/*KeyspaceName
	  Name of the keyspace to use for the request.

	*/
	KeyspaceName string
	/*TableName
	  Name of the table to use for the request.

	*/
	TableName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the add column params
func (o *AddColumnParams) WithTimeout(timeout time.Duration) *AddColumnParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add column params
func (o *AddColumnParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add column params
func (o *AddColumnParams) WithContext(ctx context.Context) *AddColumnParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add column params
func (o *AddColumnParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add column params
func (o *AddColumnParams) WithHTTPClient(client *http.Client) *AddColumnParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add column params
func (o *AddColumnParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXCassandraToken adds the xCassandraToken to the add column params
func (o *AddColumnParams) WithXCassandraToken(xCassandraToken string) *AddColumnParams {
	o.SetXCassandraToken(xCassandraToken)
	return o
}

// SetXCassandraToken adds the xCassandraToken to the add column params
func (o *AddColumnParams) SetXCassandraToken(xCassandraToken string) {
	o.XCassandraToken = xCassandraToken
}

// WithBody adds the body to the add column params
func (o *AddColumnParams) WithBody(body *models.ColumnDefinition) *AddColumnParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the add column params
func (o *AddColumnParams) SetBody(body *models.ColumnDefinition) {
	o.Body = body
}

// WithKeyspaceName adds the keyspaceName to the add column params
func (o *AddColumnParams) WithKeyspaceName(keyspaceName string) *AddColumnParams {
	o.SetKeyspaceName(keyspaceName)
	return o
}

// SetKeyspaceName adds the keyspaceName to the add column params
func (o *AddColumnParams) SetKeyspaceName(keyspaceName string) {
	o.KeyspaceName = keyspaceName
}

// WithTableName adds the tableName to the add column params
func (o *AddColumnParams) WithTableName(tableName string) *AddColumnParams {
	o.SetTableName(tableName)
	return o
}

// SetTableName adds the tableName to the add column params
func (o *AddColumnParams) SetTableName(tableName string) {
	o.TableName = tableName
}

// WriteToRequest writes these params to a swagger request
func (o *AddColumnParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-Cassandra-Token
	if err := r.SetHeaderParam("X-Cassandra-Token", o.XCassandraToken); err != nil {
		return err
	}

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param keyspaceName
	if err := r.SetPathParam("keyspaceName", o.KeyspaceName); err != nil {
		return err
	}

	// path param tableName
	if err := r.SetPathParam("tableName", o.TableName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
