// Code generated by go-swagger; DO NOT EDIT.

package schemas

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCreateKeyspaceParams creates a new CreateKeyspaceParams object
// with the default values initialized.
func NewCreateKeyspaceParams() *CreateKeyspaceParams {
	var ()
	return &CreateKeyspaceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateKeyspaceParamsWithTimeout creates a new CreateKeyspaceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateKeyspaceParamsWithTimeout(timeout time.Duration) *CreateKeyspaceParams {
	var ()
	return &CreateKeyspaceParams{

		timeout: timeout,
	}
}

// NewCreateKeyspaceParamsWithContext creates a new CreateKeyspaceParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateKeyspaceParamsWithContext(ctx context.Context) *CreateKeyspaceParams {
	var ()
	return &CreateKeyspaceParams{

		Context: ctx,
	}
}

// NewCreateKeyspaceParamsWithHTTPClient creates a new CreateKeyspaceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateKeyspaceParamsWithHTTPClient(client *http.Client) *CreateKeyspaceParams {
	var ()
	return &CreateKeyspaceParams{
		HTTPClient: client,
	}
}

/*CreateKeyspaceParams contains all the parameters to send to the API endpoint
for the create keyspace operation typically these are written to a http.Request
*/
type CreateKeyspaceParams struct {

	/*XCassandraToken
	  The token returned from the authorization endpoint. Use this token in each request.

	*/
	XCassandraToken string
	/*Body
	  A map representing a keyspace with SimpleStrategy or NetworkTopologyStrategy with default replicas of 1 and 3 respectively
	Simple:
	```json
	{ "name": "killrvideo", "replicas": 1}
	````
	Network Topology:
	```json
	{
	  "name": "killrvideo",
	   "datacenters":
	      [
	         { "name": "dc1", "replicas": 3 },
	         { "name": "dc2", "replicas": 3 },
	      ],
	}
	```

	*/
	Body string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create keyspace params
func (o *CreateKeyspaceParams) WithTimeout(timeout time.Duration) *CreateKeyspaceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create keyspace params
func (o *CreateKeyspaceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create keyspace params
func (o *CreateKeyspaceParams) WithContext(ctx context.Context) *CreateKeyspaceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create keyspace params
func (o *CreateKeyspaceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create keyspace params
func (o *CreateKeyspaceParams) WithHTTPClient(client *http.Client) *CreateKeyspaceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create keyspace params
func (o *CreateKeyspaceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXCassandraToken adds the xCassandraToken to the create keyspace params
func (o *CreateKeyspaceParams) WithXCassandraToken(xCassandraToken string) *CreateKeyspaceParams {
	o.SetXCassandraToken(xCassandraToken)
	return o
}

// SetXCassandraToken adds the xCassandraToken to the create keyspace params
func (o *CreateKeyspaceParams) SetXCassandraToken(xCassandraToken string) {
	o.XCassandraToken = xCassandraToken
}

// WithBody adds the body to the create keyspace params
func (o *CreateKeyspaceParams) WithBody(body string) *CreateKeyspaceParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create keyspace params
func (o *CreateKeyspaceParams) SetBody(body string) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateKeyspaceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-Cassandra-Token
	if err := r.SetHeaderParam("X-Cassandra-Token", o.XCassandraToken); err != nil {
		return err
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
