// Code generated by go-swagger; DO NOT EDIT.

package schemas

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteTable1Params creates a new DeleteTable1Params object
// with the default values initialized.
func NewDeleteTable1Params() *DeleteTable1Params {
	var ()
	return &DeleteTable1Params{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteTable1ParamsWithTimeout creates a new DeleteTable1Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteTable1ParamsWithTimeout(timeout time.Duration) *DeleteTable1Params {
	var ()
	return &DeleteTable1Params{

		timeout: timeout,
	}
}

// NewDeleteTable1ParamsWithContext creates a new DeleteTable1Params object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteTable1ParamsWithContext(ctx context.Context) *DeleteTable1Params {
	var ()
	return &DeleteTable1Params{

		Context: ctx,
	}
}

// NewDeleteTable1ParamsWithHTTPClient creates a new DeleteTable1Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteTable1ParamsWithHTTPClient(client *http.Client) *DeleteTable1Params {
	var ()
	return &DeleteTable1Params{
		HTTPClient: client,
	}
}

/*DeleteTable1Params contains all the parameters to send to the API endpoint
for the delete table 1 operation typically these are written to a http.Request
*/
type DeleteTable1Params struct {

	/*XCassandraToken
	  The token returned from the authorization endpoint. Use this token in each request.

	*/
	XCassandraToken string
	/*KeyspaceName
	  Name of the keyspace to use for the request.

	*/
	KeyspaceName string
	/*TableName
	  Name of the table to use for the request.

	*/
	TableName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete table 1 params
func (o *DeleteTable1Params) WithTimeout(timeout time.Duration) *DeleteTable1Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete table 1 params
func (o *DeleteTable1Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete table 1 params
func (o *DeleteTable1Params) WithContext(ctx context.Context) *DeleteTable1Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete table 1 params
func (o *DeleteTable1Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete table 1 params
func (o *DeleteTable1Params) WithHTTPClient(client *http.Client) *DeleteTable1Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete table 1 params
func (o *DeleteTable1Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXCassandraToken adds the xCassandraToken to the delete table 1 params
func (o *DeleteTable1Params) WithXCassandraToken(xCassandraToken string) *DeleteTable1Params {
	o.SetXCassandraToken(xCassandraToken)
	return o
}

// SetXCassandraToken adds the xCassandraToken to the delete table 1 params
func (o *DeleteTable1Params) SetXCassandraToken(xCassandraToken string) {
	o.XCassandraToken = xCassandraToken
}

// WithKeyspaceName adds the keyspaceName to the delete table 1 params
func (o *DeleteTable1Params) WithKeyspaceName(keyspaceName string) *DeleteTable1Params {
	o.SetKeyspaceName(keyspaceName)
	return o
}

// SetKeyspaceName adds the keyspaceName to the delete table 1 params
func (o *DeleteTable1Params) SetKeyspaceName(keyspaceName string) {
	o.KeyspaceName = keyspaceName
}

// WithTableName adds the tableName to the delete table 1 params
func (o *DeleteTable1Params) WithTableName(tableName string) *DeleteTable1Params {
	o.SetTableName(tableName)
	return o
}

// SetTableName adds the tableName to the delete table 1 params
func (o *DeleteTable1Params) SetTableName(tableName string) {
	o.TableName = tableName
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteTable1Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-Cassandra-Token
	if err := r.SetHeaderParam("X-Cassandra-Token", o.XCassandraToken); err != nil {
		return err
	}

	// path param keyspaceName
	if err := r.SetPathParam("keyspaceName", o.KeyspaceName); err != nil {
		return err
	}

	// path param tableName
	if err := r.SetPathParam("tableName", o.TableName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
