// Code generated by go-swagger; DO NOT EDIT.

package schemas

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetOneColumn1Params creates a new GetOneColumn1Params object
// with the default values initialized.
func NewGetOneColumn1Params() *GetOneColumn1Params {
	var (
		rawDefault = bool(false)
	)
	return &GetOneColumn1Params{
		Raw: &rawDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetOneColumn1ParamsWithTimeout creates a new GetOneColumn1Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetOneColumn1ParamsWithTimeout(timeout time.Duration) *GetOneColumn1Params {
	var (
		rawDefault = bool(false)
	)
	return &GetOneColumn1Params{
		Raw: &rawDefault,

		timeout: timeout,
	}
}

// NewGetOneColumn1ParamsWithContext creates a new GetOneColumn1Params object
// with the default values initialized, and the ability to set a context for a request
func NewGetOneColumn1ParamsWithContext(ctx context.Context) *GetOneColumn1Params {
	var (
		rawDefault = bool(false)
	)
	return &GetOneColumn1Params{
		Raw: &rawDefault,

		Context: ctx,
	}
}

// NewGetOneColumn1ParamsWithHTTPClient creates a new GetOneColumn1Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetOneColumn1ParamsWithHTTPClient(client *http.Client) *GetOneColumn1Params {
	var (
		rawDefault = bool(false)
	)
	return &GetOneColumn1Params{
		Raw:        &rawDefault,
		HTTPClient: client,
	}
}

/*GetOneColumn1Params contains all the parameters to send to the API endpoint
for the get one column 1 operation typically these are written to a http.Request
*/
type GetOneColumn1Params struct {

	/*XCassandraToken
	  The token returned from the authorization endpoint. Use this token in each request.

	*/
	XCassandraToken string
	/*ColumnName
	  column name

	*/
	ColumnName string
	/*KeyspaceName
	  Name of the keyspace to use for the request.

	*/
	KeyspaceName string
	/*Raw
	  Unwrap results

	*/
	Raw *bool
	/*TableName
	  Name of the table to use for the request.

	*/
	TableName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get one column 1 params
func (o *GetOneColumn1Params) WithTimeout(timeout time.Duration) *GetOneColumn1Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get one column 1 params
func (o *GetOneColumn1Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get one column 1 params
func (o *GetOneColumn1Params) WithContext(ctx context.Context) *GetOneColumn1Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get one column 1 params
func (o *GetOneColumn1Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get one column 1 params
func (o *GetOneColumn1Params) WithHTTPClient(client *http.Client) *GetOneColumn1Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get one column 1 params
func (o *GetOneColumn1Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXCassandraToken adds the xCassandraToken to the get one column 1 params
func (o *GetOneColumn1Params) WithXCassandraToken(xCassandraToken string) *GetOneColumn1Params {
	o.SetXCassandraToken(xCassandraToken)
	return o
}

// SetXCassandraToken adds the xCassandraToken to the get one column 1 params
func (o *GetOneColumn1Params) SetXCassandraToken(xCassandraToken string) {
	o.XCassandraToken = xCassandraToken
}

// WithColumnName adds the columnName to the get one column 1 params
func (o *GetOneColumn1Params) WithColumnName(columnName string) *GetOneColumn1Params {
	o.SetColumnName(columnName)
	return o
}

// SetColumnName adds the columnName to the get one column 1 params
func (o *GetOneColumn1Params) SetColumnName(columnName string) {
	o.ColumnName = columnName
}

// WithKeyspaceName adds the keyspaceName to the get one column 1 params
func (o *GetOneColumn1Params) WithKeyspaceName(keyspaceName string) *GetOneColumn1Params {
	o.SetKeyspaceName(keyspaceName)
	return o
}

// SetKeyspaceName adds the keyspaceName to the get one column 1 params
func (o *GetOneColumn1Params) SetKeyspaceName(keyspaceName string) {
	o.KeyspaceName = keyspaceName
}

// WithRaw adds the raw to the get one column 1 params
func (o *GetOneColumn1Params) WithRaw(raw *bool) *GetOneColumn1Params {
	o.SetRaw(raw)
	return o
}

// SetRaw adds the raw to the get one column 1 params
func (o *GetOneColumn1Params) SetRaw(raw *bool) {
	o.Raw = raw
}

// WithTableName adds the tableName to the get one column 1 params
func (o *GetOneColumn1Params) WithTableName(tableName string) *GetOneColumn1Params {
	o.SetTableName(tableName)
	return o
}

// SetTableName adds the tableName to the get one column 1 params
func (o *GetOneColumn1Params) SetTableName(tableName string) {
	o.TableName = tableName
}

// WriteToRequest writes these params to a swagger request
func (o *GetOneColumn1Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-Cassandra-Token
	if err := r.SetHeaderParam("X-Cassandra-Token", o.XCassandraToken); err != nil {
		return err
	}

	// path param columnName
	if err := r.SetPathParam("columnName", o.ColumnName); err != nil {
		return err
	}

	// path param keyspaceName
	if err := r.SetPathParam("keyspaceName", o.KeyspaceName); err != nil {
		return err
	}

	if o.Raw != nil {

		// query param raw
		var qrRaw bool
		if o.Raw != nil {
			qrRaw = *o.Raw
		}
		qRaw := swag.FormatBool(qrRaw)
		if qRaw != "" {
			if err := r.SetQueryParam("raw", qRaw); err != nil {
				return err
			}
		}

	}

	// path param tableName
	if err := r.SetPathParam("tableName", o.TableName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
