// Code generated by go-swagger; DO NOT EDIT.

package schemas

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetAllTablesParams creates a new GetAllTablesParams object
// with the default values initialized.
func NewGetAllTablesParams() *GetAllTablesParams {
	var (
		rawDefault = bool(false)
	)
	return &GetAllTablesParams{
		Raw: &rawDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAllTablesParamsWithTimeout creates a new GetAllTablesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAllTablesParamsWithTimeout(timeout time.Duration) *GetAllTablesParams {
	var (
		rawDefault = bool(false)
	)
	return &GetAllTablesParams{
		Raw: &rawDefault,

		timeout: timeout,
	}
}

// NewGetAllTablesParamsWithContext creates a new GetAllTablesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAllTablesParamsWithContext(ctx context.Context) *GetAllTablesParams {
	var (
		rawDefault = bool(false)
	)
	return &GetAllTablesParams{
		Raw: &rawDefault,

		Context: ctx,
	}
}

// NewGetAllTablesParamsWithHTTPClient creates a new GetAllTablesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAllTablesParamsWithHTTPClient(client *http.Client) *GetAllTablesParams {
	var (
		rawDefault = bool(false)
	)
	return &GetAllTablesParams{
		Raw:        &rawDefault,
		HTTPClient: client,
	}
}

/*GetAllTablesParams contains all the parameters to send to the API endpoint
for the get all tables operation typically these are written to a http.Request
*/
type GetAllTablesParams struct {

	/*XCassandraToken
	  The token returned from the authorization endpoint. Use this token in each request.

	*/
	XCassandraToken string
	/*KeyspaceName
	  Name of the keyspace to use for the request.

	*/
	KeyspaceName string
	/*Raw
	  Unwrap results

	*/
	Raw *bool

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get all tables params
func (o *GetAllTablesParams) WithTimeout(timeout time.Duration) *GetAllTablesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get all tables params
func (o *GetAllTablesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get all tables params
func (o *GetAllTablesParams) WithContext(ctx context.Context) *GetAllTablesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get all tables params
func (o *GetAllTablesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get all tables params
func (o *GetAllTablesParams) WithHTTPClient(client *http.Client) *GetAllTablesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get all tables params
func (o *GetAllTablesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXCassandraToken adds the xCassandraToken to the get all tables params
func (o *GetAllTablesParams) WithXCassandraToken(xCassandraToken string) *GetAllTablesParams {
	o.SetXCassandraToken(xCassandraToken)
	return o
}

// SetXCassandraToken adds the xCassandraToken to the get all tables params
func (o *GetAllTablesParams) SetXCassandraToken(xCassandraToken string) {
	o.XCassandraToken = xCassandraToken
}

// WithKeyspaceName adds the keyspaceName to the get all tables params
func (o *GetAllTablesParams) WithKeyspaceName(keyspaceName string) *GetAllTablesParams {
	o.SetKeyspaceName(keyspaceName)
	return o
}

// SetKeyspaceName adds the keyspaceName to the get all tables params
func (o *GetAllTablesParams) SetKeyspaceName(keyspaceName string) {
	o.KeyspaceName = keyspaceName
}

// WithRaw adds the raw to the get all tables params
func (o *GetAllTablesParams) WithRaw(raw *bool) *GetAllTablesParams {
	o.SetRaw(raw)
	return o
}

// SetRaw adds the raw to the get all tables params
func (o *GetAllTablesParams) SetRaw(raw *bool) {
	o.Raw = raw
}

// WriteToRequest writes these params to a swagger request
func (o *GetAllTablesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-Cassandra-Token
	if err := r.SetHeaderParam("X-Cassandra-Token", o.XCassandraToken); err != nil {
		return err
	}

	// path param keyspaceName
	if err := r.SetPathParam("keyspaceName", o.KeyspaceName); err != nil {
		return err
	}

	if o.Raw != nil {

		// query param raw
		var qrRaw bool
		if o.Raw != nil {
			qrRaw = *o.Raw
		}
		qRaw := swag.FormatBool(qrRaw)
		if qRaw != "" {
			if err := r.SetQueryParam("raw", qRaw); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
