// Code generated by go-swagger; DO NOT EDIT.

package documents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/jimdickinson/stargoat/pkg/models"
)

// CreateCollectionReader is a Reader for the CreateCollection structure.
type CreateCollectionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateCollectionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateCollectionCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewCreateCollectionUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewCreateCollectionConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateCollectionInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateCollectionCreated creates a CreateCollectionCreated with default headers values
func NewCreateCollectionCreated() *CreateCollectionCreated {
	return &CreateCollectionCreated{}
}

/*CreateCollectionCreated handles this case with default header values.

Created
*/
type CreateCollectionCreated struct {
}

func (o *CreateCollectionCreated) Error() string {
	return fmt.Sprintf("[POST /v2/namespaces/{namespace-id}/collections][%d] createCollectionCreated ", 201)
}

func (o *CreateCollectionCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateCollectionUnauthorized creates a CreateCollectionUnauthorized with default headers values
func NewCreateCollectionUnauthorized() *CreateCollectionUnauthorized {
	return &CreateCollectionUnauthorized{}
}

/*CreateCollectionUnauthorized handles this case with default header values.

Unauthorized
*/
type CreateCollectionUnauthorized struct {
}

func (o *CreateCollectionUnauthorized) Error() string {
	return fmt.Sprintf("[POST /v2/namespaces/{namespace-id}/collections][%d] createCollectionUnauthorized ", 401)
}

func (o *CreateCollectionUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateCollectionConflict creates a CreateCollectionConflict with default headers values
func NewCreateCollectionConflict() *CreateCollectionConflict {
	return &CreateCollectionConflict{}
}

/*CreateCollectionConflict handles this case with default header values.

Conflict
*/
type CreateCollectionConflict struct {
	Payload *models.Error
}

func (o *CreateCollectionConflict) Error() string {
	return fmt.Sprintf("[POST /v2/namespaces/{namespace-id}/collections][%d] createCollectionConflict  %+v", 409, o.Payload)
}

func (o *CreateCollectionConflict) GetPayload() *models.Error {
	return o.Payload
}

func (o *CreateCollectionConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateCollectionInternalServerError creates a CreateCollectionInternalServerError with default headers values
func NewCreateCollectionInternalServerError() *CreateCollectionInternalServerError {
	return &CreateCollectionInternalServerError{}
}

/*CreateCollectionInternalServerError handles this case with default header values.

Internal server error
*/
type CreateCollectionInternalServerError struct {
	Payload *models.Error
}

func (o *CreateCollectionInternalServerError) Error() string {
	return fmt.Sprintf("[POST /v2/namespaces/{namespace-id}/collections][%d] createCollectionInternalServerError  %+v", 500, o.Payload)
}

func (o *CreateCollectionInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *CreateCollectionInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
