// Code generated by go-swagger; DO NOT EDIT.

package documents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/jimdickinson/stargoat/pkg/models"
)

// DeleteDocPathReader is a Reader for the DeleteDocPath structure.
type DeleteDocPathReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteDocPathReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteDocPathNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDeleteDocPathUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteDocPathForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteDocPathInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteDocPathNoContent creates a DeleteDocPathNoContent with default headers values
func NewDeleteDocPathNoContent() *DeleteDocPathNoContent {
	return &DeleteDocPathNoContent{}
}

/*DeleteDocPathNoContent handles this case with default header values.

No Content
*/
type DeleteDocPathNoContent struct {
}

func (o *DeleteDocPathNoContent) Error() string {
	return fmt.Sprintf("[DELETE /v2/namespaces/{namespace-id}/collections/{collection-id}/{document-id}/{document-path}][%d] deleteDocPathNoContent ", 204)
}

func (o *DeleteDocPathNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteDocPathUnauthorized creates a DeleteDocPathUnauthorized with default headers values
func NewDeleteDocPathUnauthorized() *DeleteDocPathUnauthorized {
	return &DeleteDocPathUnauthorized{}
}

/*DeleteDocPathUnauthorized handles this case with default header values.

Unauthorized
*/
type DeleteDocPathUnauthorized struct {
}

func (o *DeleteDocPathUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /v2/namespaces/{namespace-id}/collections/{collection-id}/{document-id}/{document-path}][%d] deleteDocPathUnauthorized ", 401)
}

func (o *DeleteDocPathUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteDocPathForbidden creates a DeleteDocPathForbidden with default headers values
func NewDeleteDocPathForbidden() *DeleteDocPathForbidden {
	return &DeleteDocPathForbidden{}
}

/*DeleteDocPathForbidden handles this case with default header values.

Forbidden
*/
type DeleteDocPathForbidden struct {
}

func (o *DeleteDocPathForbidden) Error() string {
	return fmt.Sprintf("[DELETE /v2/namespaces/{namespace-id}/collections/{collection-id}/{document-id}/{document-path}][%d] deleteDocPathForbidden ", 403)
}

func (o *DeleteDocPathForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteDocPathInternalServerError creates a DeleteDocPathInternalServerError with default headers values
func NewDeleteDocPathInternalServerError() *DeleteDocPathInternalServerError {
	return &DeleteDocPathInternalServerError{}
}

/*DeleteDocPathInternalServerError handles this case with default header values.

Internal Server Error
*/
type DeleteDocPathInternalServerError struct {
	Payload *models.Error
}

func (o *DeleteDocPathInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /v2/namespaces/{namespace-id}/collections/{collection-id}/{document-id}/{document-path}][%d] deleteDocPathInternalServerError  %+v", 500, o.Payload)
}

func (o *DeleteDocPathInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteDocPathInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
