// Code generated by go-swagger; DO NOT EDIT.

package documents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/jimdickinson/stargoat/pkg/models"
)

// DeleteCollectionReader is a Reader for the DeleteCollection structure.
type DeleteCollectionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteCollectionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteCollectionNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDeleteCollectionUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteCollectionNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteCollectionInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteCollectionNoContent creates a DeleteCollectionNoContent with default headers values
func NewDeleteCollectionNoContent() *DeleteCollectionNoContent {
	return &DeleteCollectionNoContent{}
}

/*DeleteCollectionNoContent handles this case with default header values.

No Content
*/
type DeleteCollectionNoContent struct {
}

func (o *DeleteCollectionNoContent) Error() string {
	return fmt.Sprintf("[DELETE /v2/namespaces/{namespace-id}/collections/{collection-id}][%d] deleteCollectionNoContent ", 204)
}

func (o *DeleteCollectionNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteCollectionUnauthorized creates a DeleteCollectionUnauthorized with default headers values
func NewDeleteCollectionUnauthorized() *DeleteCollectionUnauthorized {
	return &DeleteCollectionUnauthorized{}
}

/*DeleteCollectionUnauthorized handles this case with default header values.

Unauthorized
*/
type DeleteCollectionUnauthorized struct {
}

func (o *DeleteCollectionUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /v2/namespaces/{namespace-id}/collections/{collection-id}][%d] deleteCollectionUnauthorized ", 401)
}

func (o *DeleteCollectionUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteCollectionNotFound creates a DeleteCollectionNotFound with default headers values
func NewDeleteCollectionNotFound() *DeleteCollectionNotFound {
	return &DeleteCollectionNotFound{}
}

/*DeleteCollectionNotFound handles this case with default header values.

Not Found
*/
type DeleteCollectionNotFound struct {
}

func (o *DeleteCollectionNotFound) Error() string {
	return fmt.Sprintf("[DELETE /v2/namespaces/{namespace-id}/collections/{collection-id}][%d] deleteCollectionNotFound ", 404)
}

func (o *DeleteCollectionNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteCollectionInternalServerError creates a DeleteCollectionInternalServerError with default headers values
func NewDeleteCollectionInternalServerError() *DeleteCollectionInternalServerError {
	return &DeleteCollectionInternalServerError{}
}

/*DeleteCollectionInternalServerError handles this case with default header values.

Internal server error
*/
type DeleteCollectionInternalServerError struct {
	Payload *models.Error
}

func (o *DeleteCollectionInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /v2/namespaces/{namespace-id}/collections/{collection-id}][%d] deleteCollectionInternalServerError  %+v", 500, o.Payload)
}

func (o *DeleteCollectionInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteCollectionInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
