// Code generated by go-swagger; DO NOT EDIT.

package documents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteDocParams creates a new DeleteDocParams object
// with the default values initialized.
func NewDeleteDocParams() *DeleteDocParams {
	var ()
	return &DeleteDocParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteDocParamsWithTimeout creates a new DeleteDocParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteDocParamsWithTimeout(timeout time.Duration) *DeleteDocParams {
	var ()
	return &DeleteDocParams{

		timeout: timeout,
	}
}

// NewDeleteDocParamsWithContext creates a new DeleteDocParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteDocParamsWithContext(ctx context.Context) *DeleteDocParams {
	var ()
	return &DeleteDocParams{

		Context: ctx,
	}
}

// NewDeleteDocParamsWithHTTPClient creates a new DeleteDocParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteDocParamsWithHTTPClient(client *http.Client) *DeleteDocParams {
	var ()
	return &DeleteDocParams{
		HTTPClient: client,
	}
}

/*DeleteDocParams contains all the parameters to send to the API endpoint
for the delete doc operation typically these are written to a http.Request
*/
type DeleteDocParams struct {

	/*XCassandraToken
	  The token returned from the authorization endpoint. Use this token in each request.

	*/
	XCassandraToken string
	/*CollectionID
	  the name of the collection

	*/
	CollectionID string
	/*DocumentID
	  the name of the document

	*/
	DocumentID string
	/*NamespaceID
	  the namespace that the collection is in

	*/
	NamespaceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete doc params
func (o *DeleteDocParams) WithTimeout(timeout time.Duration) *DeleteDocParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete doc params
func (o *DeleteDocParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete doc params
func (o *DeleteDocParams) WithContext(ctx context.Context) *DeleteDocParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete doc params
func (o *DeleteDocParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete doc params
func (o *DeleteDocParams) WithHTTPClient(client *http.Client) *DeleteDocParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete doc params
func (o *DeleteDocParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXCassandraToken adds the xCassandraToken to the delete doc params
func (o *DeleteDocParams) WithXCassandraToken(xCassandraToken string) *DeleteDocParams {
	o.SetXCassandraToken(xCassandraToken)
	return o
}

// SetXCassandraToken adds the xCassandraToken to the delete doc params
func (o *DeleteDocParams) SetXCassandraToken(xCassandraToken string) {
	o.XCassandraToken = xCassandraToken
}

// WithCollectionID adds the collectionID to the delete doc params
func (o *DeleteDocParams) WithCollectionID(collectionID string) *DeleteDocParams {
	o.SetCollectionID(collectionID)
	return o
}

// SetCollectionID adds the collectionId to the delete doc params
func (o *DeleteDocParams) SetCollectionID(collectionID string) {
	o.CollectionID = collectionID
}

// WithDocumentID adds the documentID to the delete doc params
func (o *DeleteDocParams) WithDocumentID(documentID string) *DeleteDocParams {
	o.SetDocumentID(documentID)
	return o
}

// SetDocumentID adds the documentId to the delete doc params
func (o *DeleteDocParams) SetDocumentID(documentID string) {
	o.DocumentID = documentID
}

// WithNamespaceID adds the namespaceID to the delete doc params
func (o *DeleteDocParams) WithNamespaceID(namespaceID string) *DeleteDocParams {
	o.SetNamespaceID(namespaceID)
	return o
}

// SetNamespaceID adds the namespaceId to the delete doc params
func (o *DeleteDocParams) SetNamespaceID(namespaceID string) {
	o.NamespaceID = namespaceID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteDocParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-Cassandra-Token
	if err := r.SetHeaderParam("X-Cassandra-Token", o.XCassandraToken); err != nil {
		return err
	}

	// path param collection-id
	if err := r.SetPathParam("collection-id", o.CollectionID); err != nil {
		return err
	}

	// path param document-id
	if err := r.SetPathParam("document-id", o.DocumentID); err != nil {
		return err
	}

	// path param namespace-id
	if err := r.SetPathParam("namespace-id", o.NamespaceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
