// Code generated by go-swagger; DO NOT EDIT.

package documents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetAllNamespacesParams creates a new GetAllNamespacesParams object
// with the default values initialized.
func NewGetAllNamespacesParams() *GetAllNamespacesParams {
	var (
		rawDefault = bool(false)
	)
	return &GetAllNamespacesParams{
		Raw: &rawDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAllNamespacesParamsWithTimeout creates a new GetAllNamespacesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAllNamespacesParamsWithTimeout(timeout time.Duration) *GetAllNamespacesParams {
	var (
		rawDefault = bool(false)
	)
	return &GetAllNamespacesParams{
		Raw: &rawDefault,

		timeout: timeout,
	}
}

// NewGetAllNamespacesParamsWithContext creates a new GetAllNamespacesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAllNamespacesParamsWithContext(ctx context.Context) *GetAllNamespacesParams {
	var (
		rawDefault = bool(false)
	)
	return &GetAllNamespacesParams{
		Raw: &rawDefault,

		Context: ctx,
	}
}

// NewGetAllNamespacesParamsWithHTTPClient creates a new GetAllNamespacesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAllNamespacesParamsWithHTTPClient(client *http.Client) *GetAllNamespacesParams {
	var (
		rawDefault = bool(false)
	)
	return &GetAllNamespacesParams{
		Raw:        &rawDefault,
		HTTPClient: client,
	}
}

/*GetAllNamespacesParams contains all the parameters to send to the API endpoint
for the get all namespaces operation typically these are written to a http.Request
*/
type GetAllNamespacesParams struct {

	/*XCassandraToken
	  The token returned from the authorization endpoint. Use this token in each request.

	*/
	XCassandraToken string
	/*Raw
	  Unwrap results

	*/
	Raw *bool

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get all namespaces params
func (o *GetAllNamespacesParams) WithTimeout(timeout time.Duration) *GetAllNamespacesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get all namespaces params
func (o *GetAllNamespacesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get all namespaces params
func (o *GetAllNamespacesParams) WithContext(ctx context.Context) *GetAllNamespacesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get all namespaces params
func (o *GetAllNamespacesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get all namespaces params
func (o *GetAllNamespacesParams) WithHTTPClient(client *http.Client) *GetAllNamespacesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get all namespaces params
func (o *GetAllNamespacesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXCassandraToken adds the xCassandraToken to the get all namespaces params
func (o *GetAllNamespacesParams) WithXCassandraToken(xCassandraToken string) *GetAllNamespacesParams {
	o.SetXCassandraToken(xCassandraToken)
	return o
}

// SetXCassandraToken adds the xCassandraToken to the get all namespaces params
func (o *GetAllNamespacesParams) SetXCassandraToken(xCassandraToken string) {
	o.XCassandraToken = xCassandraToken
}

// WithRaw adds the raw to the get all namespaces params
func (o *GetAllNamespacesParams) WithRaw(raw *bool) *GetAllNamespacesParams {
	o.SetRaw(raw)
	return o
}

// SetRaw adds the raw to the get all namespaces params
func (o *GetAllNamespacesParams) SetRaw(raw *bool) {
	o.Raw = raw
}

// WriteToRequest writes these params to a swagger request
func (o *GetAllNamespacesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-Cassandra-Token
	if err := r.SetHeaderParam("X-Cassandra-Token", o.XCassandraToken); err != nil {
		return err
	}

	if o.Raw != nil {

		// query param raw
		var qrRaw bool
		if o.Raw != nil {
			qrRaw = *o.Raw
		}
		qRaw := swag.FormatBool(qrRaw)
		if qRaw != "" {
			if err := r.SetQueryParam("raw", qRaw); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
