// Code generated by go-swagger; DO NOT EDIT.

package documents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetCollectionsParams creates a new GetCollectionsParams object
// with the default values initialized.
func NewGetCollectionsParams() *GetCollectionsParams {
	var (
		rawDefault = bool(false)
	)
	return &GetCollectionsParams{
		Raw: &rawDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetCollectionsParamsWithTimeout creates a new GetCollectionsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetCollectionsParamsWithTimeout(timeout time.Duration) *GetCollectionsParams {
	var (
		rawDefault = bool(false)
	)
	return &GetCollectionsParams{
		Raw: &rawDefault,

		timeout: timeout,
	}
}

// NewGetCollectionsParamsWithContext creates a new GetCollectionsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetCollectionsParamsWithContext(ctx context.Context) *GetCollectionsParams {
	var (
		rawDefault = bool(false)
	)
	return &GetCollectionsParams{
		Raw: &rawDefault,

		Context: ctx,
	}
}

// NewGetCollectionsParamsWithHTTPClient creates a new GetCollectionsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetCollectionsParamsWithHTTPClient(client *http.Client) *GetCollectionsParams {
	var (
		rawDefault = bool(false)
	)
	return &GetCollectionsParams{
		Raw:        &rawDefault,
		HTTPClient: client,
	}
}

/*GetCollectionsParams contains all the parameters to send to the API endpoint
for the get collections operation typically these are written to a http.Request
*/
type GetCollectionsParams struct {

	/*XCassandraToken
	  The token returned from the authorization endpoint. Use this token in each request.

	*/
	XCassandraToken string
	/*NamespaceID
	  the namespace to fetch collections for

	*/
	NamespaceID string
	/*Raw
	  Unwrap results

	*/
	Raw *bool

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get collections params
func (o *GetCollectionsParams) WithTimeout(timeout time.Duration) *GetCollectionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get collections params
func (o *GetCollectionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get collections params
func (o *GetCollectionsParams) WithContext(ctx context.Context) *GetCollectionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get collections params
func (o *GetCollectionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get collections params
func (o *GetCollectionsParams) WithHTTPClient(client *http.Client) *GetCollectionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get collections params
func (o *GetCollectionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXCassandraToken adds the xCassandraToken to the get collections params
func (o *GetCollectionsParams) WithXCassandraToken(xCassandraToken string) *GetCollectionsParams {
	o.SetXCassandraToken(xCassandraToken)
	return o
}

// SetXCassandraToken adds the xCassandraToken to the get collections params
func (o *GetCollectionsParams) SetXCassandraToken(xCassandraToken string) {
	o.XCassandraToken = xCassandraToken
}

// WithNamespaceID adds the namespaceID to the get collections params
func (o *GetCollectionsParams) WithNamespaceID(namespaceID string) *GetCollectionsParams {
	o.SetNamespaceID(namespaceID)
	return o
}

// SetNamespaceID adds the namespaceId to the get collections params
func (o *GetCollectionsParams) SetNamespaceID(namespaceID string) {
	o.NamespaceID = namespaceID
}

// WithRaw adds the raw to the get collections params
func (o *GetCollectionsParams) WithRaw(raw *bool) *GetCollectionsParams {
	o.SetRaw(raw)
	return o
}

// SetRaw adds the raw to the get collections params
func (o *GetCollectionsParams) SetRaw(raw *bool) {
	o.Raw = raw
}

// WriteToRequest writes these params to a swagger request
func (o *GetCollectionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-Cassandra-Token
	if err := r.SetHeaderParam("X-Cassandra-Token", o.XCassandraToken); err != nil {
		return err
	}

	// path param namespace-id
	if err := r.SetPathParam("namespace-id", o.NamespaceID); err != nil {
		return err
	}

	if o.Raw != nil {

		// query param raw
		var qrRaw bool
		if o.Raw != nil {
			qrRaw = *o.Raw
		}
		qRaw := swag.FormatBool(qrRaw)
		if qRaw != "" {
			if err := r.SetQueryParam("raw", qRaw); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
