// Code generated by go-swagger; DO NOT EDIT.

package documents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewPatchDocPathParams creates a new PatchDocPathParams object
// with the default values initialized.
func NewPatchDocPathParams() *PatchDocPathParams {
	var ()
	return &PatchDocPathParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPatchDocPathParamsWithTimeout creates a new PatchDocPathParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPatchDocPathParamsWithTimeout(timeout time.Duration) *PatchDocPathParams {
	var ()
	return &PatchDocPathParams{

		timeout: timeout,
	}
}

// NewPatchDocPathParamsWithContext creates a new PatchDocPathParams object
// with the default values initialized, and the ability to set a context for a request
func NewPatchDocPathParamsWithContext(ctx context.Context) *PatchDocPathParams {
	var ()
	return &PatchDocPathParams{

		Context: ctx,
	}
}

// NewPatchDocPathParamsWithHTTPClient creates a new PatchDocPathParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPatchDocPathParamsWithHTTPClient(client *http.Client) *PatchDocPathParams {
	var ()
	return &PatchDocPathParams{
		HTTPClient: client,
	}
}

/*PatchDocPathParams contains all the parameters to send to the API endpoint
for the patch doc path operation typically these are written to a http.Request
*/
type PatchDocPathParams struct {

	/*XCassandraToken
	  The token returned from the authorization endpoint. Use this token in each request.

	*/
	XCassandraToken string
	/*Body
	  The JSON document

	*/
	Body string
	/*CollectionID
	  the name of the collection

	*/
	CollectionID string
	/*DocumentID
	  the name of the document

	*/
	DocumentID string
	/*DocumentPath
	  the path in the JSON that you want to retrieve

	*/
	DocumentPath []string
	/*NamespaceID
	  the namespace that the collection is in

	*/
	NamespaceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the patch doc path params
func (o *PatchDocPathParams) WithTimeout(timeout time.Duration) *PatchDocPathParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch doc path params
func (o *PatchDocPathParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch doc path params
func (o *PatchDocPathParams) WithContext(ctx context.Context) *PatchDocPathParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch doc path params
func (o *PatchDocPathParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch doc path params
func (o *PatchDocPathParams) WithHTTPClient(client *http.Client) *PatchDocPathParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch doc path params
func (o *PatchDocPathParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXCassandraToken adds the xCassandraToken to the patch doc path params
func (o *PatchDocPathParams) WithXCassandraToken(xCassandraToken string) *PatchDocPathParams {
	o.SetXCassandraToken(xCassandraToken)
	return o
}

// SetXCassandraToken adds the xCassandraToken to the patch doc path params
func (o *PatchDocPathParams) SetXCassandraToken(xCassandraToken string) {
	o.XCassandraToken = xCassandraToken
}

// WithBody adds the body to the patch doc path params
func (o *PatchDocPathParams) WithBody(body string) *PatchDocPathParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the patch doc path params
func (o *PatchDocPathParams) SetBody(body string) {
	o.Body = body
}

// WithCollectionID adds the collectionID to the patch doc path params
func (o *PatchDocPathParams) WithCollectionID(collectionID string) *PatchDocPathParams {
	o.SetCollectionID(collectionID)
	return o
}

// SetCollectionID adds the collectionId to the patch doc path params
func (o *PatchDocPathParams) SetCollectionID(collectionID string) {
	o.CollectionID = collectionID
}

// WithDocumentID adds the documentID to the patch doc path params
func (o *PatchDocPathParams) WithDocumentID(documentID string) *PatchDocPathParams {
	o.SetDocumentID(documentID)
	return o
}

// SetDocumentID adds the documentId to the patch doc path params
func (o *PatchDocPathParams) SetDocumentID(documentID string) {
	o.DocumentID = documentID
}

// WithDocumentPath adds the documentPath to the patch doc path params
func (o *PatchDocPathParams) WithDocumentPath(documentPath []string) *PatchDocPathParams {
	o.SetDocumentPath(documentPath)
	return o
}

// SetDocumentPath adds the documentPath to the patch doc path params
func (o *PatchDocPathParams) SetDocumentPath(documentPath []string) {
	o.DocumentPath = documentPath
}

// WithNamespaceID adds the namespaceID to the patch doc path params
func (o *PatchDocPathParams) WithNamespaceID(namespaceID string) *PatchDocPathParams {
	o.SetNamespaceID(namespaceID)
	return o
}

// SetNamespaceID adds the namespaceId to the patch doc path params
func (o *PatchDocPathParams) SetNamespaceID(namespaceID string) {
	o.NamespaceID = namespaceID
}

// WriteToRequest writes these params to a swagger request
func (o *PatchDocPathParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-Cassandra-Token
	if err := r.SetHeaderParam("X-Cassandra-Token", o.XCassandraToken); err != nil {
		return err
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param collection-id
	if err := r.SetPathParam("collection-id", o.CollectionID); err != nil {
		return err
	}

	// path param document-id
	if err := r.SetPathParam("document-id", o.DocumentID); err != nil {
		return err
	}

	valuesDocumentPath := o.DocumentPath

	joinedDocumentPath := swag.JoinByFormat(valuesDocumentPath, "csv")
	// path array param document-path
	// SetPathParam does not support variadric arguments, since we used JoinByFormat
	// we can send the first item in the array as it's all the items of the previous
	// array joined together
	if len(joinedDocumentPath) > 0 {
		if err := r.SetPathParam("document-path", joinedDocumentPath[0]); err != nil {
			return err
		}
	}

	// path param namespace-id
	if err := r.SetPathParam("namespace-id", o.NamespaceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
