// Code generated by go-swagger; DO NOT EDIT.

package data

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/jimdickinson/stargoat/pkg/models"
)

// DeleteRowsReader is a Reader for the DeleteRows structure.
type DeleteRowsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteRowsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteRowsNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDeleteRowsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteRowsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteRowsNoContent creates a DeleteRowsNoContent with default headers values
func NewDeleteRowsNoContent() *DeleteRowsNoContent {
	return &DeleteRowsNoContent{}
}

/*DeleteRowsNoContent handles this case with default header values.

No Content
*/
type DeleteRowsNoContent struct {
}

func (o *DeleteRowsNoContent) Error() string {
	return fmt.Sprintf("[DELETE /v2/keyspaces/{keyspaceName}/{tableName}/{primaryKey}][%d] deleteRowsNoContent ", 204)
}

func (o *DeleteRowsNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteRowsUnauthorized creates a DeleteRowsUnauthorized with default headers values
func NewDeleteRowsUnauthorized() *DeleteRowsUnauthorized {
	return &DeleteRowsUnauthorized{}
}

/*DeleteRowsUnauthorized handles this case with default header values.

Unauthorized
*/
type DeleteRowsUnauthorized struct {
	Payload *models.Error
}

func (o *DeleteRowsUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /v2/keyspaces/{keyspaceName}/{tableName}/{primaryKey}][%d] deleteRowsUnauthorized  %+v", 401, o.Payload)
}

func (o *DeleteRowsUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteRowsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteRowsInternalServerError creates a DeleteRowsInternalServerError with default headers values
func NewDeleteRowsInternalServerError() *DeleteRowsInternalServerError {
	return &DeleteRowsInternalServerError{}
}

/*DeleteRowsInternalServerError handles this case with default header values.

Internal server error
*/
type DeleteRowsInternalServerError struct {
	Payload *models.Error
}

func (o *DeleteRowsInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /v2/keyspaces/{keyspaceName}/{tableName}/{primaryKey}][%d] deleteRowsInternalServerError  %+v", 500, o.Payload)
}

func (o *DeleteRowsInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteRowsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
