// Code generated by go-swagger; DO NOT EDIT.

package data

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetRowsParams creates a new GetRowsParams object
// with the default values initialized.
func NewGetRowsParams() *GetRowsParams {
	var ()
	return &GetRowsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetRowsParamsWithTimeout creates a new GetRowsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetRowsParamsWithTimeout(timeout time.Duration) *GetRowsParams {
	var ()
	return &GetRowsParams{

		timeout: timeout,
	}
}

// NewGetRowsParamsWithContext creates a new GetRowsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetRowsParamsWithContext(ctx context.Context) *GetRowsParams {
	var ()
	return &GetRowsParams{

		Context: ctx,
	}
}

// NewGetRowsParamsWithHTTPClient creates a new GetRowsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetRowsParamsWithHTTPClient(client *http.Client) *GetRowsParams {
	var ()
	return &GetRowsParams{
		HTTPClient: client,
	}
}

/*GetRowsParams contains all the parameters to send to the API endpoint
for the get rows operation typically these are written to a http.Request
*/
type GetRowsParams struct {

	/*XCassandraToken
	  The token returned from the authorization endpoint. Use this token in each request.

	*/
	XCassandraToken string
	/*KeyspaceName
	  Name of the keyspace to use for the request.

	*/
	KeyspaceName string
	/*TableName
	  Name of the table to use for the request.

	*/
	TableName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get rows params
func (o *GetRowsParams) WithTimeout(timeout time.Duration) *GetRowsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get rows params
func (o *GetRowsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get rows params
func (o *GetRowsParams) WithContext(ctx context.Context) *GetRowsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get rows params
func (o *GetRowsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get rows params
func (o *GetRowsParams) WithHTTPClient(client *http.Client) *GetRowsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get rows params
func (o *GetRowsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXCassandraToken adds the xCassandraToken to the get rows params
func (o *GetRowsParams) WithXCassandraToken(xCassandraToken string) *GetRowsParams {
	o.SetXCassandraToken(xCassandraToken)
	return o
}

// SetXCassandraToken adds the xCassandraToken to the get rows params
func (o *GetRowsParams) SetXCassandraToken(xCassandraToken string) {
	o.XCassandraToken = xCassandraToken
}

// WithKeyspaceName adds the keyspaceName to the get rows params
func (o *GetRowsParams) WithKeyspaceName(keyspaceName string) *GetRowsParams {
	o.SetKeyspaceName(keyspaceName)
	return o
}

// SetKeyspaceName adds the keyspaceName to the get rows params
func (o *GetRowsParams) SetKeyspaceName(keyspaceName string) {
	o.KeyspaceName = keyspaceName
}

// WithTableName adds the tableName to the get rows params
func (o *GetRowsParams) WithTableName(tableName string) *GetRowsParams {
	o.SetTableName(tableName)
	return o
}

// SetTableName adds the tableName to the get rows params
func (o *GetRowsParams) SetTableName(tableName string) {
	o.TableName = tableName
}

// WriteToRequest writes these params to a swagger request
func (o *GetRowsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-Cassandra-Token
	if err := r.SetHeaderParam("X-Cassandra-Token", o.XCassandraToken); err != nil {
		return err
	}

	// path param keyspaceName
	if err := r.SetPathParam("keyspaceName", o.KeyspaceName); err != nil {
		return err
	}

	// path param tableName
	if err := r.SetPathParam("tableName", o.TableName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
