// Code generated by go-swagger; DO NOT EDIT.

package data

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetRowWithWhereParams creates a new GetRowWithWhereParams object
// with the default values initialized.
func NewGetRowWithWhereParams() *GetRowWithWhereParams {
	var (
		rawDefault = bool(false)
	)
	return &GetRowWithWhereParams{
		Raw: &rawDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetRowWithWhereParamsWithTimeout creates a new GetRowWithWhereParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetRowWithWhereParamsWithTimeout(timeout time.Duration) *GetRowWithWhereParams {
	var (
		rawDefault = bool(false)
	)
	return &GetRowWithWhereParams{
		Raw: &rawDefault,

		timeout: timeout,
	}
}

// NewGetRowWithWhereParamsWithContext creates a new GetRowWithWhereParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetRowWithWhereParamsWithContext(ctx context.Context) *GetRowWithWhereParams {
	var (
		rawDefault = bool(false)
	)
	return &GetRowWithWhereParams{
		Raw: &rawDefault,

		Context: ctx,
	}
}

// NewGetRowWithWhereParamsWithHTTPClient creates a new GetRowWithWhereParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetRowWithWhereParamsWithHTTPClient(client *http.Client) *GetRowWithWhereParams {
	var (
		rawDefault = bool(false)
	)
	return &GetRowWithWhereParams{
		Raw:        &rawDefault,
		HTTPClient: client,
	}
}

/*GetRowWithWhereParams contains all the parameters to send to the API endpoint
for the get row with where operation typically these are written to a http.Request
*/
type GetRowWithWhereParams struct {

	/*XCassandraToken
	  The token returned from the authorization endpoint. Use this token in each request.

	*/
	XCassandraToken string
	/*Fields
	  URL escaped, comma delimited list of keys to include

	*/
	Fields *string
	/*KeyspaceName
	  Name of the keyspace to use for the request.

	*/
	KeyspaceName string
	/*PageSize
	  Restrict the number of returned items

	*/
	PageSize *int32
	/*PageState
	  Move the cursor to a particular result

	*/
	PageState *string
	/*Raw
	  Unwrap results

	*/
	Raw *bool
	/*Sort
	  Keys to sort by

	*/
	Sort *string
	/*TableName
	  Name of the table to use for the request.

	*/
	TableName string
	/*Where
	 URL escaped JSON query using the following keys:
	| Key | Operation |
	|-|-|
	| $lt | Less Than |
	| $lte | Less Than Or Equal To |
	| $gt | Greater Than |
	| $gte | Greater Than Or Equal To |
	| $ne | Not Equal To |
	| $in | Contained In |
	| $contains | Contains the given element (for lists or sets) or value (for maps) |
	| $containsKey | Contains the given key (for maps) |
	| $containsEntry | Contains the given key/value entry (for maps) |
	| $exists | A value is set for the key |

	*/
	Where string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get row with where params
func (o *GetRowWithWhereParams) WithTimeout(timeout time.Duration) *GetRowWithWhereParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get row with where params
func (o *GetRowWithWhereParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get row with where params
func (o *GetRowWithWhereParams) WithContext(ctx context.Context) *GetRowWithWhereParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get row with where params
func (o *GetRowWithWhereParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get row with where params
func (o *GetRowWithWhereParams) WithHTTPClient(client *http.Client) *GetRowWithWhereParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get row with where params
func (o *GetRowWithWhereParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXCassandraToken adds the xCassandraToken to the get row with where params
func (o *GetRowWithWhereParams) WithXCassandraToken(xCassandraToken string) *GetRowWithWhereParams {
	o.SetXCassandraToken(xCassandraToken)
	return o
}

// SetXCassandraToken adds the xCassandraToken to the get row with where params
func (o *GetRowWithWhereParams) SetXCassandraToken(xCassandraToken string) {
	o.XCassandraToken = xCassandraToken
}

// WithFields adds the fields to the get row with where params
func (o *GetRowWithWhereParams) WithFields(fields *string) *GetRowWithWhereParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the get row with where params
func (o *GetRowWithWhereParams) SetFields(fields *string) {
	o.Fields = fields
}

// WithKeyspaceName adds the keyspaceName to the get row with where params
func (o *GetRowWithWhereParams) WithKeyspaceName(keyspaceName string) *GetRowWithWhereParams {
	o.SetKeyspaceName(keyspaceName)
	return o
}

// SetKeyspaceName adds the keyspaceName to the get row with where params
func (o *GetRowWithWhereParams) SetKeyspaceName(keyspaceName string) {
	o.KeyspaceName = keyspaceName
}

// WithPageSize adds the pageSize to the get row with where params
func (o *GetRowWithWhereParams) WithPageSize(pageSize *int32) *GetRowWithWhereParams {
	o.SetPageSize(pageSize)
	return o
}

// SetPageSize adds the pageSize to the get row with where params
func (o *GetRowWithWhereParams) SetPageSize(pageSize *int32) {
	o.PageSize = pageSize
}

// WithPageState adds the pageState to the get row with where params
func (o *GetRowWithWhereParams) WithPageState(pageState *string) *GetRowWithWhereParams {
	o.SetPageState(pageState)
	return o
}

// SetPageState adds the pageState to the get row with where params
func (o *GetRowWithWhereParams) SetPageState(pageState *string) {
	o.PageState = pageState
}

// WithRaw adds the raw to the get row with where params
func (o *GetRowWithWhereParams) WithRaw(raw *bool) *GetRowWithWhereParams {
	o.SetRaw(raw)
	return o
}

// SetRaw adds the raw to the get row with where params
func (o *GetRowWithWhereParams) SetRaw(raw *bool) {
	o.Raw = raw
}

// WithSort adds the sort to the get row with where params
func (o *GetRowWithWhereParams) WithSort(sort *string) *GetRowWithWhereParams {
	o.SetSort(sort)
	return o
}

// SetSort adds the sort to the get row with where params
func (o *GetRowWithWhereParams) SetSort(sort *string) {
	o.Sort = sort
}

// WithTableName adds the tableName to the get row with where params
func (o *GetRowWithWhereParams) WithTableName(tableName string) *GetRowWithWhereParams {
	o.SetTableName(tableName)
	return o
}

// SetTableName adds the tableName to the get row with where params
func (o *GetRowWithWhereParams) SetTableName(tableName string) {
	o.TableName = tableName
}

// WithWhere adds the where to the get row with where params
func (o *GetRowWithWhereParams) WithWhere(where string) *GetRowWithWhereParams {
	o.SetWhere(where)
	return o
}

// SetWhere adds the where to the get row with where params
func (o *GetRowWithWhereParams) SetWhere(where string) {
	o.Where = where
}

// WriteToRequest writes these params to a swagger request
func (o *GetRowWithWhereParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-Cassandra-Token
	if err := r.SetHeaderParam("X-Cassandra-Token", o.XCassandraToken); err != nil {
		return err
	}

	if o.Fields != nil {

		// query param fields
		var qrFields string
		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {
			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}

	}

	// path param keyspaceName
	if err := r.SetPathParam("keyspaceName", o.KeyspaceName); err != nil {
		return err
	}

	if o.PageSize != nil {

		// query param page-size
		var qrPageSize int32
		if o.PageSize != nil {
			qrPageSize = *o.PageSize
		}
		qPageSize := swag.FormatInt32(qrPageSize)
		if qPageSize != "" {
			if err := r.SetQueryParam("page-size", qPageSize); err != nil {
				return err
			}
		}

	}

	if o.PageState != nil {

		// query param page-state
		var qrPageState string
		if o.PageState != nil {
			qrPageState = *o.PageState
		}
		qPageState := qrPageState
		if qPageState != "" {
			if err := r.SetQueryParam("page-state", qPageState); err != nil {
				return err
			}
		}

	}

	if o.Raw != nil {

		// query param raw
		var qrRaw bool
		if o.Raw != nil {
			qrRaw = *o.Raw
		}
		qRaw := swag.FormatBool(qrRaw)
		if qRaw != "" {
			if err := r.SetQueryParam("raw", qRaw); err != nil {
				return err
			}
		}

	}

	if o.Sort != nil {

		// query param sort
		var qrSort string
		if o.Sort != nil {
			qrSort = *o.Sort
		}
		qSort := qrSort
		if qSort != "" {
			if err := r.SetQueryParam("sort", qSort); err != nil {
				return err
			}
		}

	}

	// path param tableName
	if err := r.SetPathParam("tableName", o.TableName); err != nil {
		return err
	}

	// query param where
	qrWhere := o.Where
	qWhere := qrWhere
	if qWhere != "" {
		if err := r.SetQueryParam("where", qWhere); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
