// Code generated by go-swagger; DO NOT EDIT.

package data

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewPatchRowsParams creates a new PatchRowsParams object
// with the default values initialized.
func NewPatchRowsParams() *PatchRowsParams {
	var ()
	return &PatchRowsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPatchRowsParamsWithTimeout creates a new PatchRowsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPatchRowsParamsWithTimeout(timeout time.Duration) *PatchRowsParams {
	var ()
	return &PatchRowsParams{

		timeout: timeout,
	}
}

// NewPatchRowsParamsWithContext creates a new PatchRowsParams object
// with the default values initialized, and the ability to set a context for a request
func NewPatchRowsParamsWithContext(ctx context.Context) *PatchRowsParams {
	var ()
	return &PatchRowsParams{

		Context: ctx,
	}
}

// NewPatchRowsParamsWithHTTPClient creates a new PatchRowsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPatchRowsParamsWithHTTPClient(client *http.Client) *PatchRowsParams {
	var ()
	return &PatchRowsParams{
		HTTPClient: client,
	}
}

/*PatchRowsParams contains all the parameters to send to the API endpoint
for the patch rows operation typically these are written to a http.Request
*/
type PatchRowsParams struct {

	/*XCassandraToken
	  The token returned from the authorization endpoint. Use this token in each request.

	*/
	XCassandraToken string
	/*Body
	  document

	*/
	Body string
	/*KeyspaceName
	  Name of the keyspace to use for the request.

	*/
	KeyspaceName string
	/*PrimaryKey
	  Value from the primary key column for the table. Define composite keys by separating values with slashes (`val1/val2...`) in the order they were defined. </br> For example, if the composite key was defined as `PRIMARY KEY(race_year, race_name)` then the primary key in the path would be `race_year/race_name`

	*/
	PrimaryKey []string
	/*Raw*/
	Raw *bool
	/*TableName
	  Name of the table to use for the request.

	*/
	TableName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the patch rows params
func (o *PatchRowsParams) WithTimeout(timeout time.Duration) *PatchRowsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch rows params
func (o *PatchRowsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch rows params
func (o *PatchRowsParams) WithContext(ctx context.Context) *PatchRowsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch rows params
func (o *PatchRowsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch rows params
func (o *PatchRowsParams) WithHTTPClient(client *http.Client) *PatchRowsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch rows params
func (o *PatchRowsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXCassandraToken adds the xCassandraToken to the patch rows params
func (o *PatchRowsParams) WithXCassandraToken(xCassandraToken string) *PatchRowsParams {
	o.SetXCassandraToken(xCassandraToken)
	return o
}

// SetXCassandraToken adds the xCassandraToken to the patch rows params
func (o *PatchRowsParams) SetXCassandraToken(xCassandraToken string) {
	o.XCassandraToken = xCassandraToken
}

// WithBody adds the body to the patch rows params
func (o *PatchRowsParams) WithBody(body string) *PatchRowsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the patch rows params
func (o *PatchRowsParams) SetBody(body string) {
	o.Body = body
}

// WithKeyspaceName adds the keyspaceName to the patch rows params
func (o *PatchRowsParams) WithKeyspaceName(keyspaceName string) *PatchRowsParams {
	o.SetKeyspaceName(keyspaceName)
	return o
}

// SetKeyspaceName adds the keyspaceName to the patch rows params
func (o *PatchRowsParams) SetKeyspaceName(keyspaceName string) {
	o.KeyspaceName = keyspaceName
}

// WithPrimaryKey adds the primaryKey to the patch rows params
func (o *PatchRowsParams) WithPrimaryKey(primaryKey []string) *PatchRowsParams {
	o.SetPrimaryKey(primaryKey)
	return o
}

// SetPrimaryKey adds the primaryKey to the patch rows params
func (o *PatchRowsParams) SetPrimaryKey(primaryKey []string) {
	o.PrimaryKey = primaryKey
}

// WithRaw adds the raw to the patch rows params
func (o *PatchRowsParams) WithRaw(raw *bool) *PatchRowsParams {
	o.SetRaw(raw)
	return o
}

// SetRaw adds the raw to the patch rows params
func (o *PatchRowsParams) SetRaw(raw *bool) {
	o.Raw = raw
}

// WithTableName adds the tableName to the patch rows params
func (o *PatchRowsParams) WithTableName(tableName string) *PatchRowsParams {
	o.SetTableName(tableName)
	return o
}

// SetTableName adds the tableName to the patch rows params
func (o *PatchRowsParams) SetTableName(tableName string) {
	o.TableName = tableName
}

// WriteToRequest writes these params to a swagger request
func (o *PatchRowsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-Cassandra-Token
	if err := r.SetHeaderParam("X-Cassandra-Token", o.XCassandraToken); err != nil {
		return err
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param keyspaceName
	if err := r.SetPathParam("keyspaceName", o.KeyspaceName); err != nil {
		return err
	}

	valuesPrimaryKey := o.PrimaryKey

	joinedPrimaryKey := swag.JoinByFormat(valuesPrimaryKey, "csv")
	// path array param primaryKey
	// SetPathParam does not support variadric arguments, since we used JoinByFormat
	// we can send the first item in the array as it's all the items of the previous
	// array joined together
	if len(joinedPrimaryKey) > 0 {
		if err := r.SetPathParam("primaryKey", joinedPrimaryKey[0]); err != nil {
			return err
		}
	}

	if o.Raw != nil {

		// query param raw
		var qrRaw bool
		if o.Raw != nil {
			qrRaw = *o.Raw
		}
		qRaw := swag.FormatBool(qrRaw)
		if qRaw != "" {
			if err := r.SetQueryParam("raw", qRaw); err != nil {
				return err
			}
		}

	}

	// path param tableName
	if err := r.SetPathParam("tableName", o.TableName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
