// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetResponseWrapper get response wrapper
//
// swagger:model GetResponseWrapper
type GetResponseWrapper struct {

	// The count of records returned
	Count int32 `json:"count,omitempty"`

	// The data returned by the request
	Data interface{} `json:"data,omitempty"`

	// A string representing the paging state to be used on future paging requests.
	PageState string `json:"pageState,omitempty"`
}

// Validate validates this get response wrapper
func (m *GetResponseWrapper) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GetResponseWrapper) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetResponseWrapper) UnmarshalBinary(b []byte) error {
	var res GetResponseWrapper
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
