// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RowUpdate row update
//
// swagger:model RowUpdate
type RowUpdate struct {

	// The values for the named parameters used in the setExpression field
	// Required: true
	Changeset []*Changeset `json:"changeset"`
}

// Validate validates this row update
func (m *RowUpdate) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateChangeset(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RowUpdate) validateChangeset(formats strfmt.Registry) error {

	if err := validate.Required("changeset", "body", m.Changeset); err != nil {
		return err
	}

	for i := 0; i < len(m.Changeset); i++ {
		if swag.IsZero(m.Changeset[i]) { // not required
			continue
		}

		if m.Changeset[i] != nil {
			if err := m.Changeset[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("changeset" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *RowUpdate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RowUpdate) UnmarshalBinary(b []byte) error {
	var res RowUpdate
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
