// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// WriteDocResponse write doc response
//
// swagger:model WriteDocResponse
type WriteDocResponse struct {

	// document Id
	DocumentID string `json:"documentId,omitempty"`
}

// Validate validates this write doc response
func (m *WriteDocResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *WriteDocResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WriteDocResponse) UnmarshalBinary(b []byte) error {
	var res WriteDocResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
